# Generated by Django 6.0.5 on 2026-06-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0002_dynamic_units_and_reports'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storebatch',
            new_name='medical_sto_product_f93ed7_idx',
            old_name='medical_stor_product_05a77d_idx',
        ),
    ]
