# Generated by Django 6.0.5 on 2026-05-30 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0008_location_engineer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='engineer',
        ),
        migrations.AddField(
            model_name='location',
            name='engineers',
            field=models.ManyToManyField(blank=True, related_name='assigned_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
