# Generated by Django 6.0.5 on 2026-05-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0009_remove_location_engineer_location_engineers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='group_type',
            field=models.CharField(choices=[('MALE', 'Male Clinics'), ('FEMALE', 'Female Clinics'), ('SPECIALTY', 'Specialty Clinics'), ('EMERGENCY', 'Emergency Clinics'), ('CSSD', 'CSSD'), ('LAB', 'Laboratory'), ('RADIOLOGY', 'Radiology')], max_length=30),
        ),
    ]
