# Generated by Django 6.0.5 on 2026-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0010_alter_location_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='needs_spare_parts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='spare_part_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_PARTS', 'Waiting Parts'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
