# Generated by Django 6.0.5 on 2026-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0011_maintenancerequest_needs_spare_parts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='installed_spare_part',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
