# Generated by Django 6.0.5 on 2026-05-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0012_maintenancerequest_installed_spare_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_pm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_pm_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
