# Generated by Django 6.0.5 on 2026-05-31 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0014_pmhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_part_name', models.CharField(max_length=200)),
                ('installed_part_name', models.CharField(blank=True, max_length=200)),
                ('is_installed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='cssd.maintenancerequest')),
            ],
        ),
    ]
