# Generated by Django 6.0.5 on 2026-05-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0015_maintenancesparepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancesparepart',
            name='installed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maintenancesparepart',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
