# Generated by Django 6.0.5 on 2026-05-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0017_pmtemplate_asset_pm_template_pmtemplateitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmtemplateitem',
            name='item_name',
        ),
        migrations.AddField(
            model_name='pmtemplateitem',
            name='component',
            field=models.CharField(default='General', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pmtemplateitem',
            name='inspection_points',
            field=models.TextField(default='General Inspection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pmtemplateitem',
            name='system',
            field=models.CharField(default='General Inspection', max_length=200),
            preserve_default=False,
        ),
    ]
