# Generated by Django 6.0.5 on 2026-06-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0018_remove_pmtemplateitem_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssdrequest',
            name='status',
            field=models.CharField(choices=[('SENT_TO_CSSD', 'Sent to CSSD'), ('RECEIVED_BY_CSSD', 'Received by CSSD'), ('RETURNED_TO_CLINIC', 'Returned to Clinic'), ('CONFIRMED_BY_CLINIC', 'Confirmed by Clinic'), ('CLOSED', 'Closed'), ('WAITING_PARTS', 'Waiting Spare Parts')], default='SENT_TO_CSSD', max_length=30),
        ),
    ]
