# Generated by Django 6.0.5 on 2026-06-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0019_alter_cssdrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out Of Service'), ('WAITING_PARTS', 'Waiting Spare Parts')], default='ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='cssdrequest',
            name='status',
            field=models.CharField(choices=[('SENT_TO_CSSD', 'Sent to CSSD'), ('RECEIVED_BY_CSSD', 'Received by CSSD'), ('RETURNED_TO_CLINIC', 'Returned to Clinic'), ('CONFIRMED_BY_CLINIC', 'Confirmed by Clinic'), ('CLOSED', 'Closed')], default='SENT_TO_CSSD', max_length=30),
        ),
    ]
