# Generated by Django 6.0.5 on 2026-06-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0022_maintenancerequesttimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACTIVE_NEED_SPARE', 'Active - Need Spare Part'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out Of Service'), ('WAITING_PARTS', 'Waiting Spare Parts')], default='ACTIVE', max_length=30),
        ),
    ]
