# Generated by Django 6.0.5 on 2026-06-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0023_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='after_spare_part_work',
            field=models.TextField(blank=True),
        ),
    ]
