# Generated by Django 6.0.5 on 2026-06-05 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0024_maintenancerequest_after_spare_part_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='external_reporter_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_source',
            field=models.CharField(default='SYSTEM', max_length=30),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
