# Generated by Django 6.0.5 on 2026-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0025_maintenancerequest_external_reporter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_PART_APPROVAL', 'Waiting Part Approval'), ('WAITING_PARTS', 'Waiting Parts'), ('WAITING_CONFIRMATION', 'Waiting Confirmation'), ('CLOSED', 'Closed')], default='OPEN', max_length=30),
        ),
    ]
