# Generated by Django 6.0.5 on 2026-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0027_maintenancerequest_clinic_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
