# Generated by Django 6.0.5 on 2026-06-07 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0028_notification_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pmhistory',
            name='clinic_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pmhistory',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmhistory',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_pm_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmhistory',
            name='status',
            field=models.CharField(default='WAITING_CONFIRMATION', max_length=30),
        ),
        migrations.CreateModel(
            name='PMHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=200)),
                ('component', models.CharField(max_length=200)),
                ('inspection_points', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=20)),
                ('requested_spare_part', models.CharField(blank=True, max_length=200)),
                ('requested_quantity', models.PositiveIntegerField(default=0)),
                ('pm_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cssd.pmhistory')),
            ],
        ),
    ]
