# Generated by Django 6.0.5 on 2026-06-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0029_pmhistory_clinic_comment_pmhistory_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='report_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='report_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='report_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='report_manager_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='report_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pmhistory',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pmhistory',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmhistory',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pm_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmhistory',
            name='manager_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pmhistory',
            name='manager_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
