# Generated by Django 6.0.5 on 2026-06-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0030_maintenancerequest_report_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmhistory',
            name='manager_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
