# Generated by Django 6.0.5 on 2026-06-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0032_notification_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_group',
            field=models.CharField(blank=True, choices=[('MALE', 'Male Clinics'), ('FEMALE', 'Female Clinics'), ('SPECIALTY', 'Specialty Clinics'), ('EMERGENCY', 'Emergency Clinics'), ('CSSD', 'CSSD'), ('ADMIN', 'Admin'), ('ENGINEER', 'Engineer'), ('MAINTENANCE_MANAGER', 'Maintenance Manager'), ('HOSPITAL_MANAGER', 'Hospital Manager'), ('USER', 'Specific User')], max_length=30),
        ),
    ]
