# Generated by Django 6.0.6 on 2026-06-18 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0035_cssd_clinic_received_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionCleaningAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infection_cleaning_assignments', to='cssd.location')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infection_cleaning_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['clinic__group_type', 'clinic__name'],
                'unique_together': {('clinic', 'nurse', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='InfectionCleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('surface_cleaning', models.BooleanField(default=False)),
                ('chair_cleaning', models.BooleanField(default=False)),
                ('spittoon_cleaning', models.BooleanField(default=False)),
                ('suction_filter_cleaning', models.BooleanField(default=False)),
                ('handwash_basin_cleaning', models.BooleanField(default=False)),
                ('ppe_drawers_refill', models.BooleanField(default=False)),
                ('soap_refill', models.BooleanField(default=False)),
                ('sanitizer_refill', models.BooleanField(default=False)),
                ('responsible_employee', models.CharField(blank=True, max_length=150)),
                ('general_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cssd.infectioncleaningassignment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infection_cleaning_tasks', to='cssd.location')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_infection_cleaning_tasks', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infection_cleaning_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'clinic__name'],
                'unique_together': {('clinic', 'nurse', 'due_date')},
            },
        ),
    ]
