# Generated by Django 6.0.6 on 2026-06-18 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0037_infection_control_asset_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infectioncleaningassignment',
            options={'ordering': ['asset__department', 'asset__asset_number', 'clinic__group_type', 'clinic__name']},
        ),
        migrations.AlterModelOptions(
            name='infectioncleaningtask',
            options={'ordering': ['due_date', 'asset__department', 'asset__asset_number', 'clinic__name']},
        ),
        migrations.RemoveConstraint(
            model_name='infectioncleaningassignment',
            name='unique_active_infection_asset_assignment',
        ),
        migrations.AddConstraint(
            model_name='infectioncleaningassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False), ('is_active', True)), fields=('asset',), name='unique_active_infection_asset_assignment'),
        ),
    ]
